config/routes.rb
GraczSite::Application.routes.draw do

  get "pride/index"

  get "product/simple"

  get "product/classic"

  get "product/other"

  get "product/show"

  get "home/faq"

  

  scope "(:locale)", :locale => /en|th/ do
    root :to => 'home#index'
    
    match "home" => "home#index"
    match "faqs" => "home#faq"
    match "tagged" => "home#tagged"
    match "story" => "home#story"
    match "pride" => "pride#index"
    match "find_us" => "home#find_us"
    match "contact" => "home#contact"
    match "classic" => "product#classic"
    match "simple" => "product#simple"
    match "other" => "product#other"
    get "home/notsupport"
    

    resources :classic
    resources :product
    resources :life
    resources :event
    resources :planet
    resources :tip
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

 #  after_create { |admin| admin.send_reset_password_instructions }
	# def password_required?
	#   new_record? ? false : super
	# end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :simple, :classic, :other, :translations, :translations_attributes
  has_many :products

  translates :name
  accepts_nested_attributes_for :translations

  def self.to_s
    self.name
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessible :content, :cover, :date, :title, :publish, :locate, :tag_list,:teaser

  has_many :taggings
  has_many :tags, through: :taggings

  just_define_datetime_picker :date, :add_to_attr_accessible => true

  mount_uploader :cover, CoverUploader
  validates :title,:teaser, :presence => true

  def self.tagged_with(name)
    Tag.find_by_name!(name).events
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end


end

app/models/life.rb
class Life < ActiveRecord::Base
  attr_accessible :content, :cover, :title, :publish, :cover_two, :tag_list,:teaser
  has_many :taggings
  has_many :tags, through: :taggings

  mount_uploader :cover, CoverUploader
  mount_uploader :cover_two, CoverUploader
  validates :title,:teaser, :presence => true

  def self.tagged_with(name)
    Tag.find_by_name!(name).lifes
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/planet.rb
class Planet < ActiveRecord::Base
  attr_accessible :content, :cover, :title, :publish, :tag_list, :cover_two,:teaser

  has_many :taggings
  has_many :tags, through: :taggings

  mount_uploader :cover, CoverUploader
  mount_uploader :cover_two, CoverUploader
  validates :title,:teaser, :presence => true

  def self.tagged_with(name)
    Tag.find_by_name!(name).planets
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/pride.rb
class Pride < ActiveRecord::Base
  attr_accessible :description, :image, :published, :category, :translations, :translations_attributes

  mount_uploader :image, CoverUploader
  validates :description,:category, :presence => true
  translates :description
  accepts_nested_attributes_for :translations
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :description, :dimension_x, :dimension_y, :dimension_z, :model, :name, :weight, :product_images_attributes, :publish, :product_type,:stock_units_attributes, :translations, :translations_attributes
  has_many :product_images
  has_many :stock_units
  belongs_to :category

  validates :dimension_x,:dimension_y,:dimension_z, :numericality => { :greater_than_or_equal_to => 0.00 , :message => "Dimension must be number only"}
  validates :weight,:numericality => { :greater_than_or_equal_to => 0.00 , :message => "must be number only"}
  validates :product_type, :description, :model, :name, :presence => true

  accepts_nested_attributes_for :product_images,:stock_units,allow_destroy: true

  translates :name, :description
  accepts_nested_attributes_for :translations


  def self.to_s
    self.name
  end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  attr_accessible :image, :product_id
  belongs_to :product

  validates :image, :presence => true
  mount_uploader :image, ProductImageUploader
  # image_accessor :image
end

app/models/stock_unit.rb
class StockUnit < ActiveRecord::Base
  attr_accessible :packpctn, :pcsppack, :product_id, :sku

  belongs_to :product

  validates :packpctn, :pcsppack, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :taggings
  
  has_many :events, through: :taggings
  has_many :tips, through: :taggings
  has_many :lifes, through: :taggings
  has_many :planets, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  
  belongs_to :event
  belongs_to :tip
  belongs_to :life
  belongs_to :planet
  # attr_accessible :title, :body
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  attr_accessible :content, :cover, :title, :publish, :tag_list
  has_many :taggings
  has_many :tags, through: :taggings

  mount_uploader :cover, CoverUploader
   validates :title, :presence => true

   def self.tagged_with(name)
    Tag.find_by_name!(name).tips
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/where_category.rb
class WhereCategory < ActiveRecord::Base
  attr_accessible :name, :translations, :translations_attributes
  has_many :where_places

  validates :name, :presence => true

  translates :name
  accepts_nested_attributes_for :translations

  def self.to_s
    self.name
  end
end

app/models/where_place.rb
class WherePlace < ActiveRecord::Base
  attr_accessible :link, :logo, :name, :where_category_id
  belongs_to :where_category

  validates :where_category_id, :presence => true

  mount_uploader :logo, LogoUploader
end

 # :logo,

app/controllers/tip_controller.rb
class TipController < ApplicationController
	def index
		@tips = Tip.where(publish: true).reverse_order.page(params[:page]).per(15)
		@meta = {:title => 'Gracz Tips',
             :type => 'website', 
             :url => request.url, 
             :image => 'http://107.170.202.81:9292'+"#{@tips.first.cover.thumb.url}", 
             :description => 'Gracz Lorem'}
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def tag_cloud(tags, classes)
  max = tags.sort_by(&:count).last
  tags.each do |tag|
    index = tag.count.to_f / max.count * (classes.size - 1)
    yield(tag, classes[index.round])
  end
end
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/life_helper.rb
module LifeHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/pride_helper.rb
module PrideHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/tip_helper.rb
module TipHelper
end

app/views/tip/index.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
  <div class="col-sm-6 col-xs-8">
    <ol class="breadcrumb">
      <li><%= link_to t('menu.hm'), root_path %></li>
      <li class="active"><%= t('menu.tp') %></li>
    </ol>
  </div>
  <div class="col-sm-6 col-xs-4">
    <div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 cover" >
    <%= image_tag 'tips_banner.png' %>
  </div>
</div>
<div class="row row-content">
  <div class="col-xs-12">
    <p><%= t('tips.title') %></p>
  </div>
</div>
<% @tips.each_with_index do |i| %>
<div class="col-xs-4 tip-thumb">
  <!-- <div class="col-xs-12 "> -->
  <figure class="label float inside bottom fill" data-label="<%= i.title %>" >
    <%= link_to image_tag(i.cover.tip_thumb.url),"",:data => {:toggle => "modal", :target => "##{i.id}"}, :id => "t#{i.id}", :lid => "t#{i.id}" %>
  </figure>
  <!-- </div>        -->
</div>
<!-- Modal -->
<div class="modal fade bs-example-modal-xs" id="<%=i.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> <span class="glyphicon glyphicon-remove-sign"></span> </button><br>
        <%= image_tag(i.cover.tip_thumb.url) %>
        <div class="col-sm-2 col-xs-12" style="margin-top: -25px;text-align: right;float: right;">
          <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
        <div class="col-sm-2 col-xs-12" style="margin-top: -25px;text-align: right;float: right;">
          <div class="fb-share-button" data-href=<%= request.url %> data-type="button_count"></div>
        </div>
        <div class="modal-tip">
          <h4><%= i.title %></h4>
          <p><%= i.content.html_safe %></p>
        </div>
      </div>
      <div class="modal-footer">
         <% if i.tags.count != 0 %>
          <p>
            <span class="glyphicon glyphicon-tags"></span> &nbsp; <%= raw i.tags.map(&:name).map { |t| link_to t, tagged_path(:tag => t) }.join(' , ') %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>
<div class="row" id="page">
  <%= paginate @tips %>
</div>

app/views/tip/show.html.erb
<div class="row">
    <div class="col-sm-4">
		<h1 id="show-head-box">Our Tip</h1>
	</div>	
	<div class="col-sm-12 content" >
		<%=  image_tag(@tip.cover.url) %>
	</div>
</div>
<div class="row">
	<div class="col-sm-12 content" >
		<h2><%= @tip.title %></h2>
		<p>
			<%= @tip.content.html_safe %>
		</p>
		<p>
			<%= @tip.created_at %>		
		</p>
	</div>

	<div class="col-sm-12 back" >
		<%= link_to " <<< Back ", planet_index_path %>
	</div>
</div>