config/routes.rb
GraczSite::Application.routes.draw do

  get "pride/index"

  get "product/simple"

  get "product/classic"

  get "product/other"

  get "product/show"

  get "home/faq"

  

  scope "(:locale)", :locale => /en|th/ do
    root :to => 'home#index'
    
    match "home" => "home#index"
    match "faqs" => "home#faq"
    match "tagged" => "home#tagged"
    match "story" => "home#story"
    match "pride" => "pride#index"
    match "find_us" => "home#find_us"
    match "contact" => "home#contact"
    match "classic" => "product#classic"
    match "simple" => "product#simple"
    match "other" => "product#other"
    get "home/notsupport"
    

    resources :classic
    resources :product
    resources :life
    resources :event
    resources :planet
    resources :tip
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    # product = Product.where(publish: true)
    # @products = product[0..11]
    @meta = {:title => 'Gracz',
             :type => 'website',
             :url => request.url,
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png',
             :description => 'ภาชนะเกรซ คือ ภาชนะ เพื่อชีวิตที่ยืนยาว ผลิตจากเยื้อพันธุ์พืชบริสุทธิ์ ผ่านกระบวนการที่ทันสมัย ผ่านการรับรองมาตราฐานระดับนานาชาติ เพื่อให้ผลิตภัณฑ์ที่ดีที่สุดสําหรับตัวคุณ เพราะเราเชื่อว่ามนุษย์มีเพียงชีวิตเดียว และอยู่บนโลกใบเดียว เราจึงตั้งมั่นที่จะทําทุกอย่าง เพื่อดูแลทุกคนบนโลก ใบนี้ ให้มีชีวิตที่ยืนยาวและมั่นคงตลอดไป'}
  end

  def contact
    @meta = {:title => 'Gracz contact',
             :type => 'website',
             :url => request.url,
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png',
             :description => '46/151 Nuan Chan Khwaeng Nuanchan, Khet Bueng Kum Krungthep Mahanakorn 10230'}
  end

  def find_us
    @category = WhereCategory.all
    @meta = {:title => 'Gracz find us',
             :type => 'website',
             :url => request.url,
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png',
             :description => '46/151 Nuan Chan Khwaeng Nuanchan, Khet Bueng Kum Krungthep Mahanakorn 10230'}
  end

  def story
    @meta = {:title => 'Gracz story',
             :type => 'website',
             :url => request.url,
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png',
             :description => 'Gracz Lorem'}
  end

  def tagged
    @meta = {:title => 'Gracz Tagged',
             :type => 'website',
             :url => request.url,
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png',
             :description => 'Gracz Lorem'}

    if params[:tag]
      @tags = Event.where(publish: true).reverse_order.tagged_with(params[:tag])|
            Planet.where(publish: true).reverse_order.tagged_with(params[:tag])|
            Life.where(publish: true).reverse_order.tagged_with(params[:tag])|
            Tip.where(publish: true).reverse_order.tagged_with(params[:tag])

      tag = Event.where(publish: true).reverse_order.tagged_with(params[:tag])|
            Planet.where(publish: true).reverse_order.tagged_with(params[:tag])|
            Life.where(publish: true).reverse_order.tagged_with(params[:tag])|
            Tip.where(publish: true).reverse_order.tagged_with(params[:tag])

      @t = Kaminari.paginate_array(tag).page(params[:page]).per(10)
    else
      redirect_to root_path
    end
  end

  def faq
    @meta = {:title => 'Gracz FAQ',
             :type => 'website',
             :url => request.url,
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png',
             :description => 'Gracz FAQ'}
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
  <div class="col-sm-6 col-xs-8">
    <ol class="breadcrumb">
      <li><%= link_to t('menu.hm'), root_path %></li>
      <li class="active"><%= t('menu.ct') %></li>
    </ol>
  </div>
  <div class="col-sm-6 col-xs-4">
    <div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12 cover">
    <div id="map" style='height: 380px;'></div>
  </div>
</div>
<div class="row row-content ">
  <div class="col-sm-6 content map">
    <div class="col-sm-12">
      <h3 class="content-title"><%= t('contact.head1.name') %></h3>
      <p><%= t('contact.head1.sub') %><br>
      <%= t('contact.head1.add') %><br>
      <%= t('tel') %> : <%= t('contact.head1.tel1') %> <br><%= t('fax') %> : <%= t('contact.head1.fax') %></p>
    </div>
    <div class="col-sm-12">
      <%= link_to image_tag('thum_contact1.jpg'), "/assets/map01.jpg", :target => "_blank" %>
    </div>
  </div>
  <div class="col-sm-6 content map">
    <div class="col-sm-12">
      <h3 class="content-title"><%= t('contact.head2.name') %></h3>
      <p><%= t('contact.head2.sub') %><br>
      <%= t('contact.head2.add') %><br>
      <%= t('tel') %> : <%= t('contact.head2.tel1') %>, <%= t('contact.head2.tel2') %><br> <%= t('fax') %> : <%= t('contact.head2.fax') %></p>
    </div>
    <div class="col-sm-12">
      <%= link_to image_tag('thum_contact2.jpg'), "/assets/map02.jpg", :target => "_blank" %>
    </div>
  </div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
    handler.buildMap({ provider: {
      scrollwheel: false
    }, 
    internal: {id: 'map'}}, function(){
      markers = handler.addMarkers([
        {
          "lat": 13.8348551,
          "lng": 100.6371631,
          "picture": {
          "url": "http://s29.postimg.org/ra6no13hf/pin_green_solid_15.png",
          "width":  34,
          "height": 49,
          "language": "th-en"
        },
        "infowindow": "We Are Here !"
      }
    ]);

    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(16);
  });
</script>

app/views/home/faq.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
  <div class="col-sm-6 col-xs-8">
    <ol class="breadcrumb">
      <li><%= link_to t('menu.hm'), root_path %></li>
      <li class="active"><%= t('foot.col3.head') %></li>
    </ol>
  </div>
  <div class="col-sm-6 col-xs-4">
    <div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
  </div>
</div>

  
<div class="row">
    <div class="col-sm-12">
      <h2 class="faq-head-title" id="faq-top"><%= t('foot.col3.head') %></h2>
    </div>

    <div class="col-sm-12" data-spy="scroll" data-target=".nav-faq">
      <div class="nav-faq">
        <ul>
          <li><%= link_to( t('faqs.Q1'), "#faq1") %></li>
          <li><%= link_to( t('faqs.Q2'), "#faq2") %></li>
          <li><%= link_to( t('faqs.Q3'), "#faq3") %></li>
          <li><%= link_to( t('faqs.Q4'), "#faq4") %></li>
          <li><%= link_to( t('faqs.Q5'), "#faq5") %></li>
          <li><%= link_to( t('faqs.Q6'), "#faq6") %></li>
          <li><%= link_to( t('faqs.Q7'), "#faq7") %></li>
          <li><%= link_to( t('faqs.Q8'), "#faq8") %></li>
          <li><%= link_to( t('faqs.Q9'), "#faq9") %></li>
          <li><%= link_to( t('faqs.Q10'), "#faq10") %></li>
        </ul>
      </div>
    </div>
    <div class="col-sm-12 content-faq">

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq1"><%= t('faqs.Q1') %></h3>
        </div>
        <div class="panel-body">
          <p>
           <%= t('faqs.A1') %>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq2"><%= t('faqs.Q2') %></h3>
        </div>
        <div class="panel-body">
          <p>
            <ol>
              <li><%= t('faqs.A2.s1') %></li>
              <li><%= t('faqs.A2.s2') %></li>
              <li><%= t('faqs.A2.s3') %></li>
              <li><%= t('faqs.A2.s4') %></li>
              <li><%= t('faqs.A2.s5') %></li>
            </ol>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq3"><%= t('faqs.Q3') %></h3>
        </div>
        <div class="panel-body">
          <p>
            <%= t('faqs.A3.title') %>
            <ol> 
              <li><%= t('faqs.A3.s1') %></li>
              <li><%= t('faqs.A3.s2') %></li>
              <li><%= t('faqs.A3.s3') %></li>
            </ol>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq4"><%= t('faqs.Q4') %></h3>
        </div>
        <div class="panel-body">
          <p>
            <%= t('faqs.A4') %>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq5"><%= t('faqs.Q5') %></h3>
        </div>
        <div class="panel-body">
          <p>
            <%= t('faqs.A5') %>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq6"><%= t('faqs.Q6') %></h3>
        </div>
        <div class="panel-body">
          <p>
            <%= t('faqs.A6') %>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq7"><%= t('faqs.Q7') %></h3>
        </div>
        <div class="panel-body">
          <p><%= t('faqs.A7.title') %>
            <ul>
              <li><%= t('faqs.A7.s1') %></li>
              <li><%= t('faqs.A7.s2') %></li>
              <li><%= t('faqs.A7.s3') %></li>
              <li><%= t('faqs.A7.s4') %></li>
              <li><%= t('faqs.A7.s5') %></li>
              <li><%= t('faqs.A7.s6') %></li>
            </ul>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq8"><%= t('faqs.Q8') %></h3>
        </div>
        <div class="panel-body">
          <p><%= t('faqs.A8.title') %>
            <ul>
              <li><%= t('faqs.A8.s1') %></li>
              <li><%= t('faqs.A8.s2') %></li>
              <li><%= t('faqs.A8.s3') %></li>
            </ul>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq9"><%= t('faqs.Q9') %></h3>
        </div>
        <div class="panel-body">
          <p>
            <%= t('faqs.A9') %>
          </p>
        </div>
        <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title" id="faq10"><%= t('faqs.Q10') %></h3>
        </div>
        <div class="panel-body">
          <p><%= t('faqs.A10.title') %></p>
          <p><%= t('faqs.A10.s1') %></p>
          <p><%= t('faqs.A10.s2') %></p>
        </div>
         <div class="panel-footer"> <a href="#faq-top"><%= t('top') %> <span class="glyphicon glyphicon-arrow-up"></span></a> </div>
      </div>
    </div>
</div>

<script type="text/javascript">

  $(function() {
  $('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html,body').animate({
          scrollTop: target.offset().top - 25
        }, 1000);
        return false;
      }
    }
  });
});

</script>

app/views/home/find_us.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
	<div class="col-sm-6 col-xs-8">
		<ol class="breadcrumb">
			<li><%= link_to t('menu.hm'), root_path %></li>
			<li class="active"><%= t('foot.col4.head') %></li>
		</ol>
	</div>
	<div class="col-sm-6 col-xs-4">
		<div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 cover"  style="border: solid 1px gray;">
		<%= image_tag('whereToFind.png') %>
	</div>
</div>
<div class="row row-content">
	<!-- <div class="col-xs-12">
		<h1>Where to find</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div> -->
</div>
<div class="row" id="where">
	<div class="col-xs-12 box">
		<div class="panel-group" id="accordion">
			<div class="panel panel-gracz" >
				<% @category.each_with_index do |i, index| %>
				<div class="panel-heading">
					<h4 class="panel-title"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" <%= "href=" "##{i.name}"%> >
					<%= i.name %>
					</a></h4>
				</div>
				<div <%= "id=" "#{i.name}"%> class="panel-collapse collapse">
					<div class="panel-body-w">
						<div class="row row-content">
							<% WherePlace.find_all_by_where_category_id(i.id).each do |a| %>
							<div class="col-xs-3">
								<div class="col-xs-12">
									<% if a.logo.url != nil %>
									<%= link_to "#{image_tag(a.logo.logo.url)}".html_safe, "#{a.link}", :class => "tip-thumb", :target => "_blank" %>
									<% else %>
									<%= image_tag('rails.png') %>
									<% end %>
								</div>
								<!-- <div class="col-xs-12">
									<center><%= a.name %></center>
								</div> -->
							</div>
							<% end %>
						</div>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
      <div class="col-sm-6 col-xs-8">
        <ol class="breadcrumb">
			<li class="active"><%= t 'menu.hm' %></li>
		</ol>
      </div>
      <div class="col-sm-6 col-xs-4">
        <div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
      </div>
</div>


<div class="row row-content">
	<div class="col-xs-12 visible-xs cover">
		<%= image_tag "philosophy.jpg" %>
	</div>
	<div class="col-sm-8 cover1 c1 hidden-xs" style="padding-left: 0px;">
		<div class="border-wrapper" id="slider-image-wrapper">
			<div class="jcarousel">
			    <ul>
			        <li><%= image_tag "inspiration.jpg" %></li>
			        <li><%= image_tag "philosophy.jpg" %></li>
			        <li><%= image_tag "biodegradable.jpg" %></li>
			        <li><%= image_tag "sustainability.jpg" %></li>        
			    </ul>
			</div>				
		</div>
	</div>

	<div class="col-sm-4 box hidden-xs" style="padding-right: 0px;">

		 <div class="panel-group" id="accordion">
			<div class="panel panel-gracz" >
				<div class="panel-heading">

					<h4 class="panel-title">
					<a class="actives" data-toggle="collapse" data-parent="#accordion" href="#collapse1">
						<%= t 'home.inspiration' %>
					</a>
					</h4>
				</div>

				<div id="collapse1" class="panel-collapse collapse in" slide="1" >
					<div class="panel-body">
						<p>&nbsp;&nbsp;&nbsp;<%= t 'home.sub1' %>
						</br> 
						&nbsp;&nbsp;&nbsp;<%= t 'home.sub2' %>
						</br>
						&nbsp;&nbsp;&nbsp;<%= t 'home.sub3' %>
						</p>
					</div>
				</div>

				<div class="panel-heading">

					<h4 class="panel-title">
						<a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
						<%= t 'home.philosophy' %>
					</a></h4>
				</div>

				<div id="collapse2" class="panel-collapse collapse" slide="2">
					<div class="panel-body">
						<p>&nbsp;&nbsp;&nbsp;<%= t 'home.sub4' %>
						</p>
					</div>
				</div>

				<div class="panel-heading">

					<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
						<%= t 'home.biodegradable' %>
					</a></h4>
				</div>
				
				<div id="collapse3" class="panel-collapse collapse" slide="3">
					<div class="panel-body">
						<p>&nbsp;&nbsp;&nbsp;<%= t 'home.sub5' %><br>
						&nbsp;&nbsp;&nbsp;<%= t 'home.sub6' %>
						</p>
					</div>
				</div>

				<div class="panel-heading non">

					<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse4">
						<%= t 'home.sustainable' %>
					</a></h4>
				</div>
				
				<div id="collapse4" class="panel-collapse collapse" slide="4">
					<div class="panel-body">
						<p>&nbsp;&nbsp;&nbsp;<%= t 'home.sub7' %></p>
					</div>
				</div>

			</div>

		</div>
	</div>
</div>
<!-- Blog 2 -->
<div class="row row-content">	
	<div class="border-wrapper">
		<div class="col-sm-4 no-pad" >			
			<div class="col-sm-12 no-pad">
				<h3 class="title-box"><center><%= t('home.intro') %></center></h3>
			</div>

			<div class="col-sm-12">
				<div style="margin-left: -14px;">
				<%= image_tag('Gracz_Logo_02.png') %>
				</div>
				<p>&nbsp;&nbsp;&nbsp;<%= t('home.sub8.con') %>
					<ul class="intro" style="text-align: left;" >
 						<li> <%= t('home.sub8.l1') %></li>
						<li> <%= t('home.sub8.l2') %></li>
						<li> <%= t('home.sub8.l3') %></li>
						<li> <%= t('home.sub8.l4') %></li>
					</ul>
				</p>
			</div>			
		</div>
		<div class="col-sm-8 col-xs-12 cover" style="padding-right: 0px;">
			<%= image_tag("introducing_gracz_image_560x307.jpg") %>
		</div>
	</div>
</div>
<!-- Blog 3 -->


<script type="text/javascript" >

$(document).ready(function(){

  	$('#carousel').flexslider({
      animation: "slide",
      controlNav: true,
      animationLoop: true,
      slideshow: true,
      itemWidth: 200,      
      minItems: 3,
      maxItems: 3,
      directionNav: true
    });

    $('.jcarousel').jcarousel();

	$('#accordion').on('shown.bs.collapse', function () {		

		var slideNum = $(".in").attr("slide");
		slideNum -= 1;
		$('.jcarousel').jcarousel('scroll', slideNum);

	});
});

jQuery('#accordion .panel-heading a[data-toggle="collapse"]').on('click', function () {   
    jQuery('#accordion .panel-heading a[data-toggle="collapse"]').removeClass('actives');
    	$( "div" ).remove( "#slider-main" );
    	$(this).addClass('actives');
    	$(this).append('<div id="slider-main"></div>');
 });


$('#accordion .panel-heading a[class="actives"]').append('<div id="slider-main"></div>');


</script>

app/views/home/pride.html.erb
<div class="row">
<!-- 	<div class="col-sm-4">
		<h1 id="head-box">Our Pride</h1>
	</div> -->
	<div class="col-sm-12 cover">
		<%= image_tag('product-cover.jpg') %>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
</div>

app/views/home/tagged.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
      <div class="col-sm-6 col-xs-8">
        <ol class="breadcrumb">
          <li><%= link_to t('menu.hm'), root_path %></li>
        <!-- <li><a href="#">Library</a></li> -->
            <li class="active"><%= t('menu.tt') %></li>
        </ol>
      </div>
      <div class="col-sm-6 col-xs-4">
        <div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
      </div>
</div>

	
<div class="row">

	<% @t.each do |i| %>
				
		
		
		<div class="row event-content">
			<div class="col-sm-12">
				<% if i.class.name == "Event" %>
					<h2 class="title-box center"><%= link_to i.title, event_path(i) %> <small class="pull-right"><%= t('menu.ev') %></small></h2>
				<% elsif i.class.name == "Tip" %>
					<h2 class="title-box center"><%= link_to i.title, tip_path(i) %> <small class="pull-right"><%= t('menu.tp') %></small></h2>
					
				<% elsif i.class.name == "Planet" %>
					<h2 class="title-box center"><%= link_to i.title, planet_path(i) %> <small class="pull-right"><%= t('menu.pn') %></small></h2>
					
				<% elsif i.class.name == "Life" %>
					<h2 class="title-box center"><%= link_to i.title, life_path(i) %> <small class="pull-right"><%= t('menu.lf') %></small></h2>
					
				<% else %>
					<h2 class="title-box center"><%= link_to i.title, '#' %> <small class="pull-right"><%= t('menu.ev') %></small></h2>
					
				<% end %>
				
			</div>

			<div class="col-sm-12 ">	
				<div class="col-sm-5 col-xs-12 no-pad">
					<% if i.class.name == "Event" %>
						<%= link_to image_tag(i.cover.cover.url, :width => "100%"), event_path(i) %>
					<% elsif i.class.name == "Tip" %>
						<%= link_to image_tag(i.cover.cover.url, :width => "100%"), tip_path(i) %>
					<% elsif i.class.name == "Planet" %>
						<%= link_to image_tag(i.cover.cover.url, :width => "100%"), planet_path(i) %>
					<% elsif i.class.name == "Life" %>
						<%= link_to image_tag(i.cover.cover.url, :width => "100%"), life_path(i) %>
					<% else %>
						<%= link_to image_tag(i.cover.cover.url, :width => "100%"), '#' %>
					<% end %>
				</div>

				<div class="col-sm-7 col-xs-12">

					<% if i.class.name == "Event" %>
						<p> <%=  "#{i.teaser.truncate(200)}"%></p>
					<% elsif i.class.name == "Tip" %>
						<p> <%= raw "#{i.content.truncate(200)}"%></p>
					<% elsif i.class.name == "Planet" %>
						<p> <%=  "#{i.teaser.truncate(200)}"%></p>
					<% elsif i.class.name == "Life" %>
						<p> <%=  "#{i.teaser.truncate(200)}"%></p>
					<% else %>
						<p> <%=  "#{i.teaser.truncate(200)}"%></p>
					<% end %>

				</div>

				<div class="col-sm-7 col-xs-12">
					<div class="col-sm-12 col-xs-12 tags">
						<span class="glyphicon glyphicon-tags"></span> &nbsp; <%= raw i.tags.map(&:name).map { |t| link_to t, tagged_path(:tag => t) }.join(' , ') %>
					</div>
				</div>

			</div>
		</div>

	<% end %>
	
</div>
<div class="row" id="page">
		<%= paginate @t %>
</div>