config/routes.rb
GraczSite::Application.routes.draw do

  get "pride/index"

  get "product/simple"

  get "product/classic"

  get "product/other"

  get "product/show"

  get "home/faq"

  

  scope "(:locale)", :locale => /en|th/ do
    root :to => 'home#index'
    
    match "home" => "home#index"
    match "faqs" => "home#faq"
    match "tagged" => "home#tagged"
    match "story" => "home#story"
    match "pride" => "pride#index"
    match "find_us" => "home#find_us"
    match "contact" => "home#contact"
    match "classic" => "product#classic"
    match "simple" => "product#simple"
    match "other" => "product#other"
    get "home/notsupport"
    

    resources :classic
    resources :product
    resources :life
    resources :event
    resources :planet
    resources :tip
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :description, :dimension_x, :dimension_y, :dimension_z, :model, :name, :weight, :product_images_attributes, :publish, :product_type,:stock_units_attributes, :translations, :translations_attributes
  has_many :product_images
  has_many :stock_units
  belongs_to :category

  validates :dimension_x,:dimension_y,:dimension_z, :numericality => { :greater_than_or_equal_to => 0.00 , :message => "Dimension must be number only"}
  validates :weight,:numericality => { :greater_than_or_equal_to => 0.00 , :message => "must be number only"}
  validates :product_type, :description, :model, :name, :presence => true

  accepts_nested_attributes_for :product_images,:stock_units,allow_destroy: true

  translates :name, :description
  accepts_nested_attributes_for :translations


  def self.to_s
    self.name
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  def index
    @meta = {:title => 'Gracz Product',
             :type => 'website', 
             :url => request.url, 
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png', 
             :description => 'Gracz Product'}
  end

  def classic

    t = params[:type].to_i
    
    if(params[:type])
      Category.all.each do |i|
        if (t <= (Category.count+1)) && (t > 0)
          @products = Product.where("product_type = ? AND publish = ? AND category_id = ?", "Classic Product", true, "#{t}" ).reverse_order.page(params[:page]).per(15)
        else
          @products = Product.where("product_type = ? AND publish = ?", "Classic Product", true ).reverse_order.page(params[:page]).per(15)
        end
      end
    else
      @products = Product.where("product_type = ? AND publish = ?", "Classic Product", true ).reverse_order.page(params[:page]).per(15)
    end

    @meta = {:title => @products.first.name,
             :type => 'website', 
             :url => request.url, 
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png', 
             :description => @products.first.description}
  end

  def simple
    
    t = params[:type].to_i
    if(params[:type])
      Category.all.each do |i|
        if (t <= (Category.count+1)) && (t > 0)
          @products = Product.where("product_type = ? AND publish = ? AND category_id = ?", "Simple Product", true, "#{t}" ).reverse_order.page(params[:page]).per(15)
        else
          @products = Product.where("product_type = ? AND publish = ?", "Simple Product", true ).reverse_order.page(params[:page]).per(15)
        end
      end
    else
      @products = Product.where("product_type = ? AND publish = ?", "Simple Product", true ).reverse_order.page(params[:page]).per(15)
    end
    @meta = {:title => @products.first.name,
             :type => 'website', 
             :url => request.url, 
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png', 
             :description => @products.first.description}
  end

  def other
    t = params[:type].to_i
    if(params[:type])
      Category.all.each do |i|
        if (t <= (Category.count+1)) && (t > 0)
          @products = Product.where("product_type = ? AND publish = ? AND category_id = ?", "Other Product", true, "#{t}" ).reverse_order.page(params[:page]).per(15)
        else
          @products = Product.where("product_type = ? AND publish = ?", "Other Product", true ).reverse_order.page(params[:page]).per(15)
        end
      end
    else
      @products = Product.where("product_type = ? AND publish = ?", "Other Product", true ).reverse_order.page(params[:page]).per(15)
    end
    @meta = {:title => 'Other Product',
             :type => 'website', 
             :url => request.url, 
             :image => 'http://107.170.202.81:9292/assets/Gracz_Logo_02-0eb55ef7043a917cf6b745d85097c94e.png', 
             :description => 'Other Product'}
  end

  def show
    @product = Product.find(params[:id])
    @meta = {:title => @product.name,
             :type => 'website', 
             :url => request.url, 
             :image => 'http://107.170.202.81:9292' +'#{ProductImage.find(@product.id).image.thumb.url}',
             :description => @product.description}
  end

end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/classic.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
	<div class="col-sm-6 col-xs-8">
		<ol class="breadcrumb">
			<li><%= link_to t('menu.hm'), root_path %></li>
			<li><%= link_to t('menu.pd'), product_index_path %></li>
			<li class="active"><%= t('product.cs') %></li>
		</ol>
	</div>
	<div class="col-sm-6 col-xs-4">
		<div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-12 cover">
		<%= image_tag('product-cover.jpg') %>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-12">
		<h3><%= t('product.cs') %></h3>
		<p><%= t('product.sub2') %></p>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-3">
		<div class="panel-group" id="accordion">
			<div class="panel panel-gracz" >
				<div class="panel-heading">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
					<%= t('product.cs') %>
					</a>
				</div>
				<div id="collapse2" class="panel-collapse collapse in">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), classic_path %> </li>
							<% Category.where(classic: true).each do |c| %>
								<li><%= link_to "#{c.name}", classic_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>
				<div class="panel-heading">
					<!-- <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
					Gracz Simple
					</a> -->
					<%= link_to t('product.sm'), simple_path %>

				</div>
				<div id="collapse1" class="panel-collapse collapse">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), simple_path %> </li>
							<% Category.where(simple: true).each do |c| %>
							<li><%= link_to "#{c.name}", simple_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>
				<div class="panel-heading">
					<!-- <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
					Gracz Other
					</a> -->
					<%= link_to t('product.ot'), other_path %>
				</div>
				
				<div id="collapse3" class="panel-collapse collapse">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), other_path %> </li>
							<% Category.where(other: true).each do |c| %>
							<li><%= link_to "#{c.name}", other_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<%= render 'layouts/product' %>
</div>
<div class="row" id="page">
	<%= paginate @products %>
</div>

app/views/product/index.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
      <div class="col-sm-6 col-xs-8">
        <ol class="breadcrumb">
      <li><%= link_to t('menu.hm'), root_path %></li>
      <li class="active"><%= t('menu.pd') %></li>
    </ol>
      </div>
      <div class="col-sm-6 col-xs-4">
        <div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
      </div>
</div>

<div class="row row-content">
	<div class="col-sm-12 cover">
		<%= image_tag 'coverproduct.jpg' %>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-4 col-xs-4 cover-p">
		<%= link_to image_tag('classic.png'),classic_path %>
	</div>
	<div class="col-sm-4 col-xs-4 cover-p">
		<%= link_to image_tag('simple.png'),simple_path %>
	</div>
	<div class="col-sm-4 col-xs-4 cover-p">
		<%= link_to image_tag('other.png'),other_path %>
	</div>
</div>	

<div class="row row-content">
<div class="col-sm-12">
		<h1 class="gracz"><%= t 'product.head1' %></h1>
		<p><%= t 'product.sub1' %></p>
		<h3><u><%= t 'product.head2' %></u>​</h3>
		<ul style="font-size:22px;">
			<li><%= t 'product.col1' %></li>
			<li><%= t 'product.col2' %></li>
			<li><%= t 'product.col3' %></li>
      <li><%= t 'product.col4' %></li>
      <li><%= t 'product.col5' %></li>
      <li><%= t 'product.col6' %></li>
      <li><%= t 'product.col7' %></li>
      <li><%= t 'product.col8' %></li>
      <li><%= t 'product.col9' %></li>
      <li><%= t 'product.col10' %></li>
      <li><%= t 'product.col11' %></li>
      <li><%= t 'product.col12' %></li>
      <li><%= t 'product.col13' %></li>
		</ul>
	</div>
</div>

<div>
	<h3 style="margin-top: 0px;"><u><%= t 'table.title' %></u></h3>
	<div class="bs-example">

    <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th><%= t 'table.col1' %></th>
          <th><%= t 'table.col2' %></th>
          <th><%= t 'table.col3' %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td id="non"><%= t 'table.l1' %></td>
          <td><%= fa_icon "check" %></td>
          <td><%= fa_icon "check" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l2' %></td>
          <td><%= fa_icon "question" %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l3' %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l4' %></td>
          <td><%= fa_icon "check" %></td>
          <td><%= fa_icon "check" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l5' %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "check" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l6' %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "question" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l7' %></td>
          <td><%= fa_icon "question" %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l8' %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l9' %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
        <tr>
          <td id="non"><%= t 'table.l10' %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "times" %></td>
          <td><%= fa_icon "check" %></td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/product/other.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
	<div class="col-sm-6 col-xs-8">
		<ol class="breadcrumb">
			<li><%= link_to t('menu.hm'), root_path %></li>
			<li><%= link_to t('menu.pd'), product_index_path %></li>
			<li class="active"><%= t('product.ot') %></li>
		</ol>
	</div>
	<div class="col-sm-6 col-xs-4">
		<div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-12 cover">
		<%= image_tag('other_cover.jpg') %>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-12">
		<h3><%= t('product.ot1') %></h3>
		<p><%= t('product.sub4') %></p>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-3">
		<div class="panel-group" id="accordion">
			<div class="panel panel-gracz" >
				<div class="panel-heading">
					<!-- <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
					Classic Product
					</a> -->
					<%= link_to t('product.cs'), classic_path %>
				</div>
				<div id="collapse2" class="panel-collapse collapse">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), classic_path %> </li>
							<% Category.where(classic: true).each do |c| %>
							<li><%= link_to "#{c.name}", classic_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>
				<div class="panel-heading">
					<!-- <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
					Simple Products
					</a> -->
					<%= link_to t('product.sm'), simple_path %>
				</div>
				<div id="collapse1" class="panel-collapse collapse">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), simple_path %> </li>
							<% Category.where(simple: true).each do |c| %>
							<li><%= link_to "#{c.name}", simple_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>
				<div class="panel-heading">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
					<%= t('product.ot') %>
					</a>
				</div>
				
				<div id="collapse3" class="panel-collapse collapse in">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), other_path %> </li>
							<% Category.where(other: true).each do |c| %>
							<li><%= link_to "#{c.name}", other_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<%= render 'layouts/product' %>
</div>
<div class="row" id="page">
	<%= paginate @products %>
</div>

app/views/product/show.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
  <div class="col-sm-12 col-xs-12">
    <ol class="breadcrumb">
      <li><%= link_to t('menu.hm'), root_path %></li>
      <li><%= link_to t('menu.pd'), product_index_path %></li>
      <li>

        <% if @product.product_type == "Simple Product" %>
          <%= link_to t('product.sm') , "/#{params[:locale]}/#{ @product.product_type.split[0].downcase}" %>
        <% end %>

        <% if @product.product_type == "Classic Product" %>
          <%= link_to t('product.cs') , "/#{params[:locale]}/#{ @product.product_type.split[0].downcase}" %>
        <% end %>

        <% if @product.product_type == "Other Product" %>
          <%= link_to t('product.ot') , "/#{params[:locale]}/#{ @product.product_type.split[0].downcase}" %>
        <% end %>

      </li>
      <li class="active"><%= @product.name %></li>
    </ol>
  </div>
  <!-- <div class="col-sm-6 col-xs-4 no-pad">
    <div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
  </div> -->
</div>

<div class="row row-content">
  <div class="col-sm-5 col-xs-12">
    <div id="slider-show" class="flexslider">
      <ul class="slides slides-p">
        <% ProductImage.find_all_by_product_id(@product.id).each do |a| %>
        <li>
          <%=  image_tag(a.image.thumb1.url) %>
        </li>
        <% end %>
      </ul>
    </div>
    <p><%= t('product.details.more') %> :</p>
    <div id="carousel" class="flexslider">
      <ul class="slides product-colo">
        <% ProductImage.find_all_by_product_id(@product.id).each do |a| %>
        <li class="border-wrapper" >
          <%=  image_tag a.image.mini_thumb.url %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-sm-7 col-xs-12">
    
    <div class="col-sm-9 col-xs-9" style="color:#60a306;">
      <h3 style="font-weight: 300;"><%= @product.name %></h3>
    </div>
    <div class="col-sm-2 col-xs-2" style="margin-top: 29px;text-align: right;margin-bottom: 25px;">
      <div class="fb-share-button" data-href=<%= request.url %> data-type="button_count"></div>
    </div>

    <div class="col-sm-12 underline">
      <%= @product.description %>
    </div>
    <div class="col-sm-12" style="padding-top:20px;">
      <div class="table-responsive">
        <table class="table">
            <tbody>
                <tr>
                    <td class="product-table"><%=  image_tag('model.jpg') %><%= t('product.details.model') %> :</td>
                    <td class="product-table"><%= @product.model %></td>
                </tr>
                <tr>
                    <td class="product-table"><%=  image_tag('dimensional.jpg') %><%= t('product.details.dimen') %> :</td>
                    <td class="product-table"><%= "#{@product.dimension_x} X #{@product.dimension_y} X #{@product.dimension_z}" %></td>
                </tr>
                <tr>
                    <td class="product-table"><%=  image_tag('weight.jpg') %><%= t('product.details.weight') %> :</td>
                    <td class="product-table"><%= @product.weight %> <%= t('product.details.g') %></td>
                </tr>
                <tr>
                    <td class="product-table"><%=  image_tag('product-detail.jpg') %><%= t('product.details.detail') %> :</td>
                    <td class="product-table">
                      <% StockUnit.find_all_by_product_id(@product.id).each_with_index do |a, index| %>
                        <%= "#{a.pcsppack} ".html_safe %> <%= t('product.details.unit1') %></br>
                        <%= "#{a.packpctn} ".html_safe %> <%= t('product.details.unit2') %></br>
                        <%= "#{a.pcsppack * a.packpctn} ".html_safe %> <%= t('product.details.unit3') %></br></br>
                      <% end %> 
                    </td>
                </tr>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="back">
  <% if @product.product_type == "Simple Product" %>
    <%= link_to t('back') , "/#{params[:locale]}/#{ @product.product_type.split[0].downcase}" %>
  <% end %>

  <% if @product.product_type == "Classic Product" %>
    <%= link_to t('back') , "/#{params[:locale]}/#{ @product.product_type.split[0].downcase}" %>
  <% end %>

  <% if @product.product_type == "Other Product" %>
    <%= link_to t('back') , "/#{params[:locale]}/#{ @product.product_type.split[0].downcase}" %>
  <% end %>
</div>

<script type="text/javascript" >
  $(document).ready(function(){
  // $(window).load(function() {
  // The slider-show being synced must be initialized first
    $('#slider-show').flexslider({
      animation: "slide",
      controlNav: false,
      animationLoop: false,
      slideshow: false,
      directionNav: false,
      sync: "#carousel"
    });

    $('#carousel').flexslider({
      animation: "slide",
      controlNav: false,
      animationLoop: false,
      slideshow: false,
      itemWidth: 100,
      itemMargin: 10,
      minItems: 3,
      maxItems: 3,
      asNavFor: '#slider-show'
    });
  });
</script>

app/views/product/simple.html.erb
<div class="row" style="margin-bottom: 10px;margin-left: 0px;">
	<div class="col-sm-6 col-xs-8">
		<ol class="breadcrumb">
			<li><%= link_to t('menu.hm'), root_path %></li>
			<li><%= link_to t('menu.pd'), product_index_path %></li>
			<li class="active"><%= t('product.sm') %></li>
		</ol>
	</div>
	<div class="col-sm-6 col-xs-4">
		<div class="fb-like" id="face" data-href="https://www.facebook.com/gracz.co.th" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-12 cover">
		<%= image_tag('simple_cover.jpg') %>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-12">
		<h3><%= t('product.sm') %></h3>
		<p><%= t('product.sub3') %></p>
	</div>
</div>
<div class="row row-content">
	<div class="col-sm-3">
		<div class="panel-group" id="accordion">
			<div class="panel panel-gracz" >
				<div class="panel-heading">
					<!-- <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
					Classic Product
					</a> -->
					<%= link_to t('product.cs'), classic_path %>
				</div>
				<div id="collapse2" class="panel-collapse collapse">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), classic_path %> </li>
							<% Category.where(classic: true).each do |c| %>
							<li><%= link_to "#{c.name}", classic_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>
				<div class="panel-heading">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
					<%= t('product.sm') %>
					</a>
				</div>
				<div id="collapse1" class="panel-collapse collapse in">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), simple_path %> </li>
							<% Category.where(simple: true).each do |c| %>
							<li><%= link_to "#{c.name}", simple_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>				
				<div class="panel-heading">
					<!-- <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
					Other Product
					</a> -->
					<%= link_to t('product.ot'), other_path %>
				</div>
				
				<div id="collapse3" class="panel-collapse collapse">
					<div class="panel-body l-menu">
						<ul>
							<li> <%= link_to t('all'), other_path %> </li>
							<% Category.where(other: true).each do |c| %>
							<li><%= link_to "#{c.name}", other_path(:type => "#{c.id}") %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<%= render 'layouts/product' %>
</div>
<div class="row" id="page">
	<%= paginate @products %>
</div>